---
mobSpawn:
  item:
    material: "ZOMBIE_HEAD"
    amount: 1
    displayName: "&b&lMob Spawn"
    headData: null
    headOwner: null
    lore:
    - "&7Разрешать мобам появляться на вашем острове."
    - ""
    - "&b&lЗначение"
    - "&7%value%"
    slot: 10
  defaultValue: "true"
leafDecay:
  item:
    material: "OAK_LEAVES"
    amount: 1
    displayName: "&b&lLeaf Decay"
    headData: null
    headOwner: null
    lore:
    - "&7Allow leaves to decay on your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 11
  defaultValue: "true"
weather:
  item:
    material: "SNOWBALL"
    amount: 1
    displayName: "&b&lIsland Weather"
    headData: null
    headOwner: null
    lore:
    - "&7Change the weather of your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 12
  defaultValue: "DEFAULT"
time:
  item:
    material: "CLOCK"
    amount: 1
    displayName: "&b&lIsland Time"
    headData: null
    headOwner: null
    lore:
    - "&7Change your Island time."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 13
  defaultValue: "DEFAULT"
endermanGrief:
  item:
    material: "ENDER_PEARL"
    amount: 1
    displayName: "&b&lEnderman Grief"
    headData: null
    headOwner: null
    lore:
    - "&7Allow enderman to grief your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 14
  defaultValue: "true"
liquidFlow:
  item:
    material: "WATER_BUCKET"
    amount: 1
    displayName: "&b&lLiquid Flow"
    headData: null
    headOwner: null
    lore:
    - "&7Allow Water and Lava to flow on your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 15
  defaultValue: "true"
tntDamage:
  item:
    material: "TNT"
    amount: 1
    displayName: "&b&lTnT Damage"
    headData: null
    headOwner: null
    lore:
    - "&7Allow TnT to explode on your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 16
  defaultValue: "true"
fireSpread:
  item:
    material: "FLINT_AND_STEEL"
    amount: 1
    displayName: "&b&lFire Spread"
    headData: null
    headOwner: null
    lore:
    - "&7Allow fire to spread on your Island."
    - ""
    - "&b&lValue"
    - "&7%value%"
    slot: 19
  defaultValue: "true"
